package Vista;

import javax.swing.*;

public class registrarClase extends JFrame{
    private JPanel panel;
    private JTextField txtNombreGim;
    private JTextField txtDescripcion;
    private JTextField txtCupo;
    private JLabel errores;
    private JButton btnRegistrarGimnasio;
    private JComboBox cmbInstructor;
    private JComboBox cmbDiaFechaInicio;
    private JComboBox cmbMesFechaInicio;
    private JComboBox cbmEstado;
    private JTextField txtCosto;
    private JPanel principalRegistrarClase;
    private JComboBox cmbDiaFechaFin;
    private JComboBox cmbMesFechaFin;
    private JCheckBox chkLunes;
    private JCheckBox chkMartes;
    private JCheckBox chkMiercoles;
    private JCheckBox chkJueves;
    private JCheckBox chkViernes;
    private JCheckBox chkSabado;
    private JCheckBox chkDomingo;
    private JComboBox horaEntradaLunes;
    private JComboBox minutoEntradaLunes;
    private JComboBox horaCierreLunes;
    private JComboBox minutoCierreLunes;
    private JComboBox horaEntradaMartes;
    private JComboBox horaCierreMartes;
    private JComboBox minutoEntradaMartes;
    private JComboBox minutoCierreMartes;
    private JComboBox horaEntradaMiercoles;
    private JComboBox minutoEntradaMiercoles;
    private JComboBox horaCierreMiercoles;
    private JComboBox minutoCierreMiercoles;
    private JComboBox horaEntradaJueves;
    private JComboBox minutoEntradaJueves;
    private JComboBox horaCierreJueves;
    private JComboBox minutoCierreJueves;
    private JComboBox horaEntradaViernes;
    private JComboBox minutoEntradaViernes;
    private JComboBox horaCierreViernes;
    private JComboBox minutoCierreViernes;
    private JComboBox horaEntradaSabado;
    private JComboBox minutoEntradaSabado;
    private JComboBox horaCierreSabado;
    private JComboBox minutoCierreSabado;
    private JComboBox horaEntradaDomingo;
    private JComboBox horaCierreDomingo;
    private JComboBox minutoEntradaDomingo;
    private JComboBox minutoCierreDomingo;
}
