/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class buscarGimnasios extends javax.swing.JFrame {

    /**
     * Creates new form buscarActividad
     */
    public buscarGimnasios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxGimnasio = new javax.swing.JComboBox<>();
        ingresoBuscar = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        comboBoxUbicacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGimnasios = new javax.swing.JTable();
        comboBoxEquipos = new javax.swing.JComboBox<>();
        comboBoxMateriales = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUbicaciones = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        editarGimnasioSeleccionadoButton = new javax.swing.JButton();
        eliminarGimnasioSeleccionadoButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableHistorialEquipo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableMateriales = new javax.swing.JTable();
        editarUbicacionSeleccionadaButton = new javax.swing.JButton();
        eliminarUbicacionSeleccionadaButton = new javax.swing.JButton();
        editarEquipoButton = new javax.swing.JButton();
        eliminarEquipoSeleccionadoButton = new javax.swing.JButton();
        mostrarHistorialDeMantenimientoEquipoButton = new javax.swing.JButton();
        mostrarHistorialDeMantenimientoButton = new javax.swing.JButton();
        editarMaterialButton = new javax.swing.JButton();
        eliminarMaterialSeleccionadoButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableEquipos = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableMantenimientoMaterial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setPreferredSize(new java.awt.Dimension(1050, 610));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Gimnasios");
        principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Busqueda de Gimnasios por Nombre:");
        principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Ubicaciones:");
        principal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Seleccione un gimnasio");
        principal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        comboBoxGimnasio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxGimnasio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxGimnasio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principal.add(comboBoxGimnasio, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 170, 40));

        ingresoBuscar.setBackground(new java.awt.Color(242, 250, 255));
        ingresoBuscar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principal.add(ingresoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 160, 30));

        buscarButton.setBackground(new java.awt.Color(242, 250, 255));
        buscarButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        buscarButton.setText("Buscar");
        principal.add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 110, 30));

        comboBoxUbicacion.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxUbicacion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principal.add(comboBoxUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 170, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tableGimnasios.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tableGimnasios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableGimnasios);

        principal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 600, 140));

        comboBoxEquipos.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxEquipos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxEquipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEquiposActionPerformed(evt);
            }
        });
        principal.add(comboBoxEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 170, 30));

        comboBoxMateriales.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMateriales.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMateriales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principal.add(comboBoxMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 170, 30));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tableUbicaciones.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        tableUbicaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableUbicaciones);

        principal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 290, 110));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("para ver sus detalles");
        principal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        editarGimnasioSeleccionadoButton.setBackground(new java.awt.Color(242, 250, 255));
        editarGimnasioSeleccionadoButton.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        editarGimnasioSeleccionadoButton.setText("Editar Gimnasio Seleccionado");
        principal.add(editarGimnasioSeleccionadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 180, 30));

        eliminarGimnasioSeleccionadoButton.setBackground(new java.awt.Color(242, 250, 255));
        eliminarGimnasioSeleccionadoButton.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        eliminarGimnasioSeleccionadoButton.setText("Eliminar Gimnasio Seleccionado");
        eliminarGimnasioSeleccionadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarGimnasioSeleccionadoButtonActionPerformed(evt);
            }
        });
        principal.add(eliminarGimnasioSeleccionadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 180, 30));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel6.setText("Equipos:");
        principal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setText("Materiales:");
        principal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, -1, -1));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tableHistorialEquipo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        tableHistorialEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableHistorialEquipo);

        principal.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 150, 150));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        tableMateriales.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        tableMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableMateriales);

        principal.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 340, 110));

        editarUbicacionSeleccionadaButton.setBackground(new java.awt.Color(242, 250, 255));
        editarUbicacionSeleccionadaButton.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        editarUbicacionSeleccionadaButton.setText("Editar Ubicacion Seleccionada");
        principal.add(editarUbicacionSeleccionadaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, 30));

        eliminarUbicacionSeleccionadaButton.setBackground(new java.awt.Color(242, 250, 255));
        eliminarUbicacionSeleccionadaButton.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        eliminarUbicacionSeleccionadaButton.setText("Eliminar Ubicacion Seleccionada");
        principal.add(eliminarUbicacionSeleccionadaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, 30));

        editarEquipoButton.setBackground(new java.awt.Color(242, 250, 255));
        editarEquipoButton.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        editarEquipoButton.setText("Editar Equipo Seleccionado");
        principal.add(editarEquipoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, 30));

        eliminarEquipoSeleccionadoButton.setBackground(new java.awt.Color(242, 250, 255));
        eliminarEquipoSeleccionadoButton.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        eliminarEquipoSeleccionadoButton.setText("Eliminar Equipo Seleccionado");
        principal.add(eliminarEquipoSeleccionadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 180, 30));

        mostrarHistorialDeMantenimientoEquipoButton.setBackground(new java.awt.Color(242, 250, 255));
        mostrarHistorialDeMantenimientoEquipoButton.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        mostrarHistorialDeMantenimientoEquipoButton.setText("Mostrar Historial de Mantenimiento");
        principal.add(mostrarHistorialDeMantenimientoEquipoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 180, 30));

        mostrarHistorialDeMantenimientoButton.setBackground(new java.awt.Color(242, 250, 255));
        mostrarHistorialDeMantenimientoButton.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        mostrarHistorialDeMantenimientoButton.setText("Mostrar Historial de Mantenimiento");
        principal.add(mostrarHistorialDeMantenimientoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 180, 30));
        
        editarMaterialButton.setBackground(new java.awt.Color(242, 250, 255));
        editarMaterialButton.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        editarMaterialButton.setText("Editar Material Seleccionado");
        principal.add(editarMaterialButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 180, 30));

        eliminarMaterialSeleccionadoButton.setBackground(new java.awt.Color(242, 250, 255));
        eliminarMaterialSeleccionadoButton.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        eliminarMaterialSeleccionadoButton.setText("Eliminar Material Seleccionado");
        principal.add(eliminarMaterialSeleccionadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 180, 30));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        tableEquipos.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        tableEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tableEquipos);

        principal.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 340, 110));

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));

        tableMantenimientoMaterial.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        tableMantenimientoMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tableMantenimientoMaterial);

        principal.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 150, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarGimnasioSeleccionadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarGimnasioSeleccionadoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarGimnasioSeleccionadoButtonActionPerformed

    private void comboBoxEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEquiposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buscarButton;
    public javax.swing.JComboBox<String> comboBoxEquipos;
    public javax.swing.JComboBox<String> comboBoxGimnasio;
    public javax.swing.JComboBox<String> comboBoxMateriales;
    public javax.swing.JComboBox<String> comboBoxUbicacion;
    public javax.swing.JButton editarEquipoButton;
    public javax.swing.JButton editarGimnasioSeleccionadoButton;
    public javax.swing.JButton editarMaterialButton;
    public javax.swing.JButton editarUbicacionSeleccionadaButton;
    public javax.swing.JButton eliminarEquipoSeleccionadoButton;
    public javax.swing.JButton eliminarGimnasioSeleccionadoButton;
    public javax.swing.JButton eliminarMaterialSeleccionadoButton;
    public javax.swing.JButton eliminarUbicacionSeleccionadaButton;
    public javax.swing.JTextField ingresoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JButton mostrarHistorialDeMantenimientoButton;
    public javax.swing.JButton mostrarHistorialDeMantenimientoEquipoButton;
    public javax.swing.JPanel principal;
    public javax.swing.JTable tableEquipos;
    public javax.swing.JTable tableGimnasios;
    public javax.swing.JTable tableHistorialEquipo;
    public javax.swing.JTable tableMantenimientoMaterial;
    public javax.swing.JTable tableMateriales;
    public javax.swing.JTable tableUbicaciones;
    // End of variables declaration//GEN-END:variables
}
