/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class buscarActividad extends javax.swing.JFrame {

    /**
     * Creates new form buscarActividad
     */
    public buscarActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalBuscarActividad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxCampoBusqueda = new javax.swing.JComboBox<>();
        textField1 = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        comboBox1 = new javax.swing.JComboBox<>();
        editarButton = new javax.swing.JButton();
        elimanrSeleccionadoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalBuscarActividad.setBackground(new java.awt.Color(255, 255, 255));
        principalBuscarActividad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Actividad");
        principalBuscarActividad.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1000, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Buscar Actividad por:");
        principalBuscarActividad.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Seleccione la Actividad a Editar");
        principalBuscarActividad.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Coinicidencias:");
        principalBuscarActividad.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        comboBoxCampoBusqueda.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxCampoBusqueda.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxCampoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalBuscarActividad.add(comboBoxCampoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, 30));

        textField1.setBackground(new java.awt.Color(242, 250, 255));
        textField1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalBuscarActividad.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 200, 30));

        buscarButton.setBackground(new java.awt.Color(242, 250, 255));
        buscarButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        buscarButton.setText("Buscar");
        principalBuscarActividad.add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 170, 30));

        comboBox1.setBackground(new java.awt.Color(242, 250, 255));
        comboBox1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalBuscarActividad.add(comboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 260, 30));

        editarButton.setBackground(new java.awt.Color(242, 250, 255));
        editarButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        principalBuscarActividad.add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 320, 180, 30));

        elimanrSeleccionadoButton.setBackground(new java.awt.Color(242, 250, 255));
        elimanrSeleccionadoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        elimanrSeleccionadoButton.setText("Eliminar Seleccionado");
        principalBuscarActividad.add(elimanrSeleccionadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 180, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        principalBuscarActividad.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 630, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalBuscarActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalBuscarActividad, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buscarButton;
    public javax.swing.JComboBox<String> comboBox1;
    public javax.swing.JComboBox<String> comboBoxCampoBusqueda;
    public javax.swing.JButton editarButton;
    public javax.swing.JButton elimanrSeleccionadoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel principalBuscarActividad;
    public javax.swing.JTable table1;
    public javax.swing.JTextField textField1;
    // End of variables declaration//GEN-END:variables
}
