/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;

/**
 *
 * @author joshe
 */
public class buscarFacturas extends javax.swing.JFrame {

    /**
     * Creates new form buscarActividad
     */
    public buscarFacturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxCampoBusqueda = new javax.swing.JComboBox<>();
        ingresoBusqueda = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        comboBox1 = new JComboBox<Integer>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEcontrados = new javax.swing.JTable();
        comboBoxMes = new javax.swing.JComboBox<>();
        comboBoxYear = new JComboBox<Integer>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetalles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Facturas");
        principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1000, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Buscar Facturas por:");
        principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Detalles de:");
        principal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Coinicidencias:");
        principal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        comboBoxCampoBusqueda.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxCampoBusqueda.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxCampoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principal.add(comboBoxCampoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, 30));

        ingresoBusqueda.setBackground(new java.awt.Color(242, 250, 255));
        ingresoBusqueda.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principal.add(ingresoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 200, 30));

        buscarButton.setBackground(new java.awt.Color(242, 250, 255));
        buscarButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        buscarButton.setText("Buscar");
        principal.add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 170, 30));

        comboBox1.setBackground(new java.awt.Color(242, 250, 255));
        comboBox1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //comboBox1.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principal.add(comboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 170, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tableEcontrados.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tableEcontrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableEcontrados);

        principal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 630, 320));

        comboBoxMes.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMes.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principal.add(comboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 90, 30));

        comboBoxYear.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxYear.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //comboBoxYear.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principal.add(comboBoxYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 90, 30));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tableDetalles.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tableDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDetalles);

        principal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 230, 290, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buscarButton;
    public JComboBox<Integer> comboBox1;
    public javax.swing.JComboBox<String> comboBoxCampoBusqueda;
    public javax.swing.JComboBox<String> comboBoxMes;
    public JComboBox<Integer> comboBoxYear;
    public javax.swing.JTextField ingresoBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel principal;
    public javax.swing.JTable tableDetalles;
    public javax.swing.JTable tableEcontrados;
    // End of variables declaration//GEN-END:variables
}
