/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class editarMiembros extends javax.swing.JFrame {

    /**
     * Creates new form registroMiembros
     */
    public editarMiembros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principaleditarMiembros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        escogerFotoButton = new javax.swing.JButton();
        cambiarFotoButton = new javax.swing.JButton();
        foto = new javax.swing.JLabel();
        cambiarNombreButton = new javax.swing.JButton();
        cambiarApellidosButton = new javax.swing.JButton();
        cambiarTelefonoButton = new javax.swing.JButton();
        cambiarDireccionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principaleditarMiembros.setBackground(new java.awt.Color(255, 255, 255));
        principaleditarMiembros.setPreferredSize(new java.awt.Dimension(400, 450));
        principaleditarMiembros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Miembro");
        principaleditarMiembros.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombres");
        principaleditarMiembros.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos");
        principaleditarMiembros.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Telefono");
        principaleditarMiembros.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("Dirección");
        principaleditarMiembros.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Foto Escogida:");
        principaleditarMiembros.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, 20));

        txtNombres.setBackground(new java.awt.Color(242, 250, 255));
        txtNombres.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principaleditarMiembros.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 30));

        txtApellidos.setBackground(new java.awt.Color(242, 250, 255));
        txtApellidos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principaleditarMiembros.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 230, 30));

        txtTelefono.setBackground(new java.awt.Color(242, 250, 255));
        txtTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principaleditarMiembros.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 230, 30));

        txtDireccion.setBackground(new java.awt.Color(242, 250, 255));
        txtDireccion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principaleditarMiembros.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, 30));

        escogerFotoButton.setBackground(new java.awt.Color(242, 250, 255));
        escogerFotoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        escogerFotoButton.setText("Escoger Foto");
        principaleditarMiembros.add(escogerFotoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, 30));

        cambiarFotoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarFotoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarFotoButton.setText("Cambiar Foto");
        principaleditarMiembros.add(cambiarFotoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 150, 30));

        foto.setText(".");
        principaleditarMiembros.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 130, 60));

        cambiarNombreButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarNombreButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarNombreButton.setText("Cambiar Nombre");
        principaleditarMiembros.add(cambiarNombreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 150, 30));

        cambiarApellidosButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarApellidosButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarApellidosButton.setText("Cambiar Apellidos");
        principaleditarMiembros.add(cambiarApellidosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 150, 30));

        cambiarTelefonoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarTelefonoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarTelefonoButton.setText("Cambiar Telefono");
        principaleditarMiembros.add(cambiarTelefonoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 150, 30));

        cambiarDireccionButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarDireccionButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarDireccionButton.setText("Cambiar Dirección");
        principaleditarMiembros.add(cambiarDireccionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principaleditarMiembros, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principaleditarMiembros, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cambiarApellidosButton;
    public javax.swing.JButton cambiarDireccionButton;
    public javax.swing.JButton cambiarFotoButton;
    public javax.swing.JButton cambiarNombreButton;
    public javax.swing.JButton cambiarTelefonoButton;
    public javax.swing.JButton escogerFotoButton;
    public javax.swing.JLabel foto;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel principaleditarMiembros;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
