/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class editarGimnasios extends javax.swing.JFrame {

    /**
     * Creates new form editarGimnasios
     */
    public editarGimnasios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalEditarGimnasio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cambiarNombreButton = new javax.swing.JButton();
        cambiarDireccionButton = new javax.swing.JButton();
        cambiarTelefonoButton = new javax.swing.JButton();
        cambiarHorarioButton = new javax.swing.JButton();
        comboBoxHoraInicio = new javax.swing.JComboBox<>();
        comboBoxMinutoInicio = new javax.swing.JComboBox<>();
        comboBoxHoraFin = new javax.swing.JComboBox<>();
        comboBoxMinutoFin = new javax.swing.JComboBox<>();
        txtNombreGim = new javax.swing.JTextField();
        txtDireccionGim = new javax.swing.JTextField();
        txtTelefonoGim = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalEditarGimnasio.setBackground(new java.awt.Color(255, 255, 255));
        principalEditarGimnasio.setPreferredSize(new java.awt.Dimension(700, 280));
        principalEditarGimnasio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Gimnasio");
        principalEditarGimnasio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        principalEditarGimnasio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Direccion");
        principalEditarGimnasio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Telefono");
        principalEditarGimnasio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("Horario");
        principalEditarGimnasio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jLabel6.setText("Hora Inicio: ");
        principalEditarGimnasio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jLabel7.setText("Hora Fin: ");
        principalEditarGimnasio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        cambiarNombreButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarNombreButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarNombreButton.setText("Cambiar Nombre");
        principalEditarGimnasio.add(cambiarNombreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 150, 30));

        cambiarDireccionButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarDireccionButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarDireccionButton.setText("Cambiar Dirección");
        principalEditarGimnasio.add(cambiarDireccionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 150, 30));

        cambiarTelefonoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarTelefonoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarTelefonoButton.setText("Cambiar Telefono");
        principalEditarGimnasio.add(cambiarTelefonoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 150, 30));

        cambiarHorarioButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarHorarioButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarHorarioButton.setText("Combiar Horario");
        principalEditarGimnasio.add(cambiarHorarioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, 30));

        comboBoxHoraInicio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxHoraInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarGimnasio.add(comboBoxHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 30));

        comboBoxMinutoInicio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMinutoInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMinutoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarGimnasio.add(comboBoxMinutoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, 30));

        comboBoxHoraFin.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxHoraFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxHoraFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarGimnasio.add(comboBoxHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 30));

        comboBoxMinutoFin.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMinutoFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMinutoFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarGimnasio.add(comboBoxMinutoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, 30));

        txtNombreGim.setBackground(new java.awt.Color(242, 250, 255));
        principalEditarGimnasio.add(txtNombreGim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 290, 30));

        txtDireccionGim.setBackground(new java.awt.Color(242, 250, 255));
        principalEditarGimnasio.add(txtDireccionGim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 290, 30));

        txtTelefonoGim.setBackground(new java.awt.Color(242, 250, 255));
        principalEditarGimnasio.add(txtTelefonoGim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalEditarGimnasio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalEditarGimnasio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cambiarDireccionButton;
    public javax.swing.JButton cambiarHorarioButton;
    public javax.swing.JButton cambiarNombreButton;
    public javax.swing.JButton cambiarTelefonoButton;
    public javax.swing.JComboBox<String> comboBoxHoraFin;
    public javax.swing.JComboBox<String> comboBoxHoraInicio;
    public javax.swing.JComboBox<String> comboBoxMinutoFin;
    public javax.swing.JComboBox<String> comboBoxMinutoInicio;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel principalEditarGimnasio;
    public javax.swing.JTextField txtDireccionGim;
    public javax.swing.JTextField txtNombreGim;
    public javax.swing.JTextField txtTelefonoGim;
    // End of variables declaration//GEN-END:variables
}
