/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;

/**
 *
 * @author joshe
 */
public class editarActividad extends javax.swing.JFrame {

    /**
     * Creates new form editarActividad
     */
    public editarActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreAct = new javax.swing.JTextField();
        textField1 = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCupo = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        comboBoxGimnasios = new javax.swing.JComboBox<>();
        comboBoxUbicaciones = new javax.swing.JComboBox<>();
        cbmEstado = new javax.swing.JComboBox<>();
        cmbInstructor = new javax.swing.JComboBox<>();
        cambiarNombreButton = new javax.swing.JButton();
        cambiarCodigoButton = new javax.swing.JButton();
        cambiarDescripcionButton = new javax.swing.JButton();
        cambiarCupoButton = new javax.swing.JButton();
        cambiarUbicacionButton = new javax.swing.JButton();
        cambiarEstadoButton = new javax.swing.JButton();
        cambiarInstructorButton = new javax.swing.JButton();
        cambiarCostoButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboBoxDiasSemana = new javax.swing.JComboBox<>();
        cmbDiaFechaInicio = new JComboBox<Integer>();
        cmbMesFechaInicio = new javax.swing.JComboBox<>();
        cmbYearFechaInicio = new JComboBox<Integer>();
        cmbDiaFechaFin = new JComboBox<Integer>();
        cmbMesFechaFin = new javax.swing.JComboBox<>();
        cmbYearFechaFinal = new JComboBox<Integer>();
        comboBoxHoraInicio = new javax.swing.JComboBox<>();
        comboBoxMinutoInicio = new javax.swing.JComboBox<>();
        comboBoxHoraFin = new javax.swing.JComboBox<>();
        comboBoxMinutoFin = new javax.swing.JComboBox<>();
        cambiarDiaButton = new javax.swing.JButton();
        cambiarHorarioButton = new javax.swing.JButton();
        Errores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setPreferredSize(new java.awt.Dimension(620, 680));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Actividad");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 620, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Codigo");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Descripcion");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("Cupo");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel6.setText("Ubicacion");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setText("Estado");
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Instructor");
        panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel9.setText("Costo");
        panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel10.setText("Horario");
        panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        txtNombreAct.setBackground(new java.awt.Color(242, 250, 255));
        txtNombreAct.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        panel.add(txtNombreAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 270, 30));

        textField1.setBackground(new java.awt.Color(242, 250, 255));
        textField1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        panel.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 270, 30));

        txtDescripcion.setBackground(new java.awt.Color(242, 250, 255));
        txtDescripcion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        panel.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 270, 30));

        txtCupo.setBackground(new java.awt.Color(242, 250, 255));
        txtCupo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        panel.add(txtCupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 270, 30));

        txtCosto.setBackground(new java.awt.Color(242, 250, 255));
        txtCosto.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        panel.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 270, 30));

        comboBoxGimnasios.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxGimnasios.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxGimnasios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(comboBoxGimnasios, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 130, 30));

        comboBoxUbicaciones.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxUbicaciones.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxUbicaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(comboBoxUbicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 130, 30));

        cbmEstado.setBackground(new java.awt.Color(242, 250, 255));
        cbmEstado.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cbmEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(cbmEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 270, 30));

        cmbInstructor.setBackground(new java.awt.Color(242, 250, 255));
        cmbInstructor.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbInstructor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInstructorActionPerformed(evt);
            }
        });
        panel.add(cmbInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 270, 30));

        cambiarNombreButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarNombreButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarNombreButton.setText("Cambiar Nombre");
        cambiarNombreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarNombreButtonActionPerformed(evt);
            }
        });
        panel.add(cambiarNombreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 160, 30));

        cambiarCodigoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarCodigoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarCodigoButton.setText("Cambiar Codigo");
        panel.add(cambiarCodigoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 160, 30));

        cambiarDescripcionButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarDescripcionButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarDescripcionButton.setText("Cambiar Descripcion");
        panel.add(cambiarDescripcionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 30));

        cambiarCupoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarCupoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarCupoButton.setText("Cambiar Cupo");
        panel.add(cambiarCupoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 160, 30));

        cambiarUbicacionButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarUbicacionButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarUbicacionButton.setText("Cambiar Ubicacion");
        panel.add(cambiarUbicacionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 160, 30));

        cambiarEstadoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarEstadoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarEstadoButton.setText("Cambiar Estado");
        panel.add(cambiarEstadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 160, 30));

        cambiarInstructorButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarInstructorButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarInstructorButton.setText("Cambiar Instructor");
        panel.add(cambiarInstructorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 160, 30));

        cambiarCostoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarCostoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarCostoButton.setText("Cambiar Costo");
        panel.add(cambiarCostoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 160, 30));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel11.setText("Dia");
        panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel12.setText("Fecha Inicio");
        panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel13.setText("Fecha Final");
        panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        jLabel14.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel14.setText("Hora Inicio: ");
        panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        jLabel15.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel15.setText("Hora Fin: ");
        panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, -1, -1));

        comboBoxDiasSemana.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxDiasSemana.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxDiasSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(comboBoxDiasSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 110, 30));

        cmbDiaFechaInicio.setBackground(new java.awt.Color(242, 250, 255));
        cmbDiaFechaInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //cmbDiaFechaInicio.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(cmbDiaFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 30));

        cmbMesFechaInicio.setBackground(new java.awt.Color(242, 250, 255));
        cmbMesFechaInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbMesFechaInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(cmbMesFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, 30));

        cmbYearFechaInicio.setBackground(new java.awt.Color(242, 250, 255));
        cmbYearFechaInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //cmbYearFechaInicio.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(cmbYearFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, 30));

        cmbDiaFechaFin.setBackground(new java.awt.Color(242, 250, 255));
        cmbDiaFechaFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //cmbDiaFechaFin.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(cmbDiaFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, 30));

        cmbMesFechaFin.setBackground(new java.awt.Color(242, 250, 255));
        cmbMesFechaFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbMesFechaFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(cmbMesFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, 30));

        cmbYearFechaFinal.setBackground(new java.awt.Color(242, 250, 255));
        cmbYearFechaFinal.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //cmbYearFechaFinal.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(cmbYearFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, 30));

        comboBoxHoraInicio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxHoraInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(comboBoxHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, 30));

        comboBoxMinutoInicio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMinutoInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMinutoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(comboBoxMinutoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, -1, 30));

        comboBoxHoraFin.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxHoraFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxHoraFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(comboBoxHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, 30));

        comboBoxMinutoFin.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMinutoFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMinutoFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(comboBoxMinutoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, -1, 30));

        cambiarDiaButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarDiaButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarDiaButton.setText("Cambiar Dia");
        panel.add(cambiarDiaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, 30));

        cambiarHorarioButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarHorarioButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarHorarioButton.setText("Cambiar Horario");
        cambiarHorarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarHorarioButtonActionPerformed(evt);
            }
        });
        panel.add(cambiarHorarioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, -1, 30));

        Errores.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Errores.setText("Errores");
        panel.add(Errores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 570, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbInstructorActionPerformed

    private void cambiarNombreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarNombreButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarNombreButtonActionPerformed

    private void cambiarHorarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarHorarioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarHorarioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Errores;
    public javax.swing.JButton cambiarCodigoButton;
    public javax.swing.JButton cambiarCostoButton;
    public javax.swing.JButton cambiarCupoButton;
    public javax.swing.JButton cambiarDescripcionButton;
    public javax.swing.JButton cambiarDiaButton;
    public javax.swing.JButton cambiarEstadoButton;
    public javax.swing.JButton cambiarHorarioButton;
    public javax.swing.JButton cambiarInstructorButton;
    public javax.swing.JButton cambiarNombreButton;
    public javax.swing.JButton cambiarUbicacionButton;
    public javax.swing.JComboBox<String> cbmEstado;
    public JComboBox<Integer> cmbDiaFechaFin;
    public JComboBox<Integer> cmbDiaFechaInicio;
    public javax.swing.JComboBox<String> cmbInstructor;
    public javax.swing.JComboBox<String> cmbMesFechaFin;
    public javax.swing.JComboBox<String> cmbMesFechaInicio;
    public JComboBox<Integer> cmbYearFechaFinal;
    public JComboBox<Integer> cmbYearFechaInicio;
    public javax.swing.JComboBox<String> comboBoxDiasSemana;
    public javax.swing.JComboBox<String> comboBoxGimnasios;
    public javax.swing.JComboBox<String> comboBoxHoraFin;
    public javax.swing.JComboBox<String> comboBoxHoraInicio;
    public javax.swing.JComboBox<String> comboBoxMinutoFin;
    public javax.swing.JComboBox<String> comboBoxMinutoInicio;
    public javax.swing.JComboBox<String> comboBoxUbicaciones;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel panel;
    public javax.swing.JTextField textField1;
    public javax.swing.JTextField txtCosto;
    public javax.swing.JTextField txtCupo;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtNombreAct;
    // End of variables declaration//GEN-END:variables
}
