/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class editarUbicaciones extends javax.swing.JFrame {

    /**
     * Creates new form editarUbicaciones
     */
    public editarUbicaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cambiarCodigoButton = new javax.swing.JButton();
        cambiarNombreButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setPreferredSize(new java.awt.Dimension(430, 250));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Ubicación");
        principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 430, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Codigo");
        principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");
        principal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(242, 250, 255));
        txtCodigo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        principal.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 30));

        txtNombre.setBackground(new java.awt.Color(242, 250, 255));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        principal.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 30));

        cambiarCodigoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarCodigoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarCodigoButton.setText("Cambiar Codigo");
        principal.add(cambiarCodigoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 140, 30));

        cambiarNombreButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarNombreButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarNombreButton.setText("Cambiar Nombre");
        principal.add(cambiarNombreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cambiarCodigoButton;
    public javax.swing.JButton cambiarNombreButton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel principal;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
