/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class editarPersonal extends javax.swing.JFrame {

    /**
     * Creates new form registroMiembros
     */
    public editarPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalEditarPersonal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRol = new javax.swing.JTextField();
        escogerFotoButton = new javax.swing.JButton();
        cambiarFotoButton = new javax.swing.JButton();
        foto = new javax.swing.JLabel();
        cambiarNombresButton = new javax.swing.JButton();
        cambiarApellidosButton = new javax.swing.JButton();
        cambiarTelefonoButton = new javax.swing.JButton();
        cambiarRolButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cambiarClaveButton = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cambiarDireccionButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cambiarJornadaButton = new javax.swing.JButton();
        cmbJornada = new javax.swing.JComboBox<>();
        txtClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalEditarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        principalEditarPersonal.setPreferredSize(new java.awt.Dimension(430, 660));
        principalEditarPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Personal");
        principalEditarPersonal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombres");
        principalEditarPersonal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos");
        principalEditarPersonal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Telefono");
        principalEditarPersonal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("Rol");
        principalEditarPersonal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Foto Escogida:");
        principalEditarPersonal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, -1, 20));

        txtNombres.setBackground(new java.awt.Color(242, 250, 255));
        txtNombres.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalEditarPersonal.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 30));

        txtApellidos.setBackground(new java.awt.Color(242, 250, 255));
        txtApellidos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalEditarPersonal.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 230, 30));

        txtTelefono.setBackground(new java.awt.Color(242, 250, 255));
        txtTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalEditarPersonal.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, 30));

        txtRol.setBackground(new java.awt.Color(242, 250, 255));
        txtRol.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalEditarPersonal.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 30));

        escogerFotoButton.setBackground(new java.awt.Color(242, 250, 255));
        escogerFotoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        escogerFotoButton.setText("Escoger Foto");
        principalEditarPersonal.add(escogerFotoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 120, 30));

        cambiarFotoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarFotoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarFotoButton.setText("Cambiar Foto");
        principalEditarPersonal.add(cambiarFotoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 150, 30));

        foto.setText(".");
        principalEditarPersonal.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 130, 60));

        cambiarNombresButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarNombresButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarNombresButton.setText("Cambiar Nombre");
        principalEditarPersonal.add(cambiarNombresButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 150, 30));

        cambiarApellidosButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarApellidosButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarApellidosButton.setText("Cambiar Apellidos");
        principalEditarPersonal.add(cambiarApellidosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 150, 30));

        cambiarTelefonoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarTelefonoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarTelefonoButton.setText("Cambiar Telefono");
        principalEditarPersonal.add(cambiarTelefonoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 150, 30));

        cambiarRolButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarRolButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarRolButton.setText("Cambiar Rol");
        cambiarRolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarRolButtonActionPerformed(evt);
            }
        });
        principalEditarPersonal.add(cambiarRolButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 150, 30));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel6.setText("Clave");
        principalEditarPersonal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 20));

        cambiarClaveButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarClaveButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarClaveButton.setText("Cambiar Clave");
        cambiarClaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarClaveButtonActionPerformed(evt);
            }
        });
        principalEditarPersonal.add(cambiarClaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 150, 30));

        txtDireccion.setBackground(new java.awt.Color(242, 250, 255));
        txtDireccion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalEditarPersonal.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 230, 30));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setText("Dirección");
        principalEditarPersonal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 20));

        cambiarDireccionButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarDireccionButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarDireccionButton.setText("Cambiar Dirección");
        principalEditarPersonal.add(cambiarDireccionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 150, 30));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel9.setText("Jornada");
        principalEditarPersonal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 20));

        cambiarJornadaButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarJornadaButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarJornadaButton.setText("Cambiar Jornada");
        cambiarJornadaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarJornadaButtonActionPerformed(evt);
            }
        });
        principalEditarPersonal.add(cambiarJornadaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 150, 30));

        cmbJornada.setBackground(new java.awt.Color(242, 250, 255));
        cmbJornada.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarPersonal.add(cmbJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 230, 30));

        txtClave.setBackground(new java.awt.Color(242, 250, 255));
        txtClave.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalEditarPersonal.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalEditarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalEditarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarClaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarClaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarClaveButtonActionPerformed

    private void cambiarRolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarRolButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarRolButtonActionPerformed

    private void cambiarJornadaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarJornadaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarJornadaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cambiarApellidosButton;
    public javax.swing.JButton cambiarClaveButton;
    public javax.swing.JButton cambiarDireccionButton;
    public javax.swing.JButton cambiarFotoButton;
    public javax.swing.JButton cambiarJornadaButton;
    public javax.swing.JButton cambiarNombresButton;
    public javax.swing.JButton cambiarRolButton;
    public javax.swing.JButton cambiarTelefonoButton;
    public javax.swing.JComboBox<String> cmbJornada;
    public javax.swing.JButton escogerFotoButton;
    public javax.swing.JLabel foto;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel principalEditarPersonal;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JPasswordField txtClave;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtRol;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
