/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;

/**
 *
 * @author joshe
 */
public class editarMateriales extends javax.swing.JFrame {

    /**
     * Creates new form editarEquipos
     */
    public editarMateriales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalEditarMateriales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionMaterial = new javax.swing.JTextArea();
        txtEstadoMaterial = new javax.swing.JTextField();
        cambiarEstadoButton = new javax.swing.JButton();
        cambiarDescripcionButton = new javax.swing.JButton();
        cambiarFechaButton = new javax.swing.JButton();
        dayComboBox = new JComboBox<Integer>();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new JComboBox<Integer>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalEditarMateriales.setBackground(new java.awt.Color(255, 255, 255));
        principalEditarMateriales.setPreferredSize(new java.awt.Dimension(700, 300));
        principalEditarMateriales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Material");
        principalEditarMateriales.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Estado: ");
        principalEditarMateriales.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Descripcion:");
        principalEditarMateriales.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Fecha Mantenimiento: ");
        principalEditarMateriales.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtDescripcionMaterial.setColumns(20);
        txtDescripcionMaterial.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtDescripcionMaterial.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionMaterial);

        principalEditarMateriales.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 280, 100));

        txtEstadoMaterial.setBackground(new java.awt.Color(242, 250, 255));
        txtEstadoMaterial.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalEditarMateriales.add(txtEstadoMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 170, 30));

        cambiarEstadoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarEstadoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarEstadoButton.setText("Cambiar Estado");
        principalEditarMateriales.add(cambiarEstadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 30));

        cambiarDescripcionButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarDescripcionButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarDescripcionButton.setText("Cambiar Descripcion");
        principalEditarMateriales.add(cambiarDescripcionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, 30));

        cambiarFechaButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarFechaButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarFechaButton.setText("Cambiar Fecha");
        principalEditarMateriales.add(cambiarFechaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, 30));

        dayComboBox.setBackground(new java.awt.Color(242, 250, 255));
        dayComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //dayComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarMateriales.add(dayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, 30));

        monthComboBox.setBackground(new java.awt.Color(242, 250, 255));
        monthComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarMateriales.add(monthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, 30));

        yearComboBox.setBackground(new java.awt.Color(242, 250, 255));
        yearComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //yearComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarMateriales.add(yearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalEditarMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalEditarMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cambiarDescripcionButton;
    public javax.swing.JButton cambiarEstadoButton;
    public javax.swing.JButton cambiarFechaButton;
    public JComboBox<Integer> dayComboBox;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> monthComboBox;
    public javax.swing.JPanel principalEditarMateriales;
    public javax.swing.JTextArea txtDescripcionMaterial;
    public javax.swing.JTextField txtEstadoMaterial;
    public JComboBox<Integer> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
