/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;

/**
 *
 * @author joshe
 */
public class editarEquipos extends javax.swing.JFrame {

    /**
     * Creates new form editarEquipos
     */
    public editarEquipos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalEditarEquipo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionEquipo = new javax.swing.JTextArea();
        txtEstadoEquipo = new javax.swing.JTextField();
        cambiarEstadoButton = new javax.swing.JButton();
        cambiarDescripcionButton = new javax.swing.JButton();
        cambiarFechaProximaButton = new javax.swing.JButton();
        dayProxComboBox = new JComboBox<Integer>();
        monthProxComboBox = new javax.swing.JComboBox<>();
        yearProxComboBox = new JComboBox<Integer>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalEditarEquipo.setBackground(new java.awt.Color(255, 255, 255));
        principalEditarEquipo.setPreferredSize(new java.awt.Dimension(700, 300));
        principalEditarEquipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Equipo");
        principalEditarEquipo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Estado: ");
        principalEditarEquipo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Descripcion:");
        principalEditarEquipo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Fecha Proxima: ");
        principalEditarEquipo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtDescripcionEquipo.setBackground(new java.awt.Color(242, 250, 255));
        txtDescripcionEquipo.setColumns(20);
        txtDescripcionEquipo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtDescripcionEquipo.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionEquipo);

        principalEditarEquipo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 280, 100));

        txtEstadoEquipo.setBackground(new java.awt.Color(242, 250, 255));
        txtEstadoEquipo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalEditarEquipo.add(txtEstadoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 170, 30));

        cambiarEstadoButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarEstadoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarEstadoButton.setText("Cambiar Estado");
        principalEditarEquipo.add(cambiarEstadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 30));

        cambiarDescripcionButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarDescripcionButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarDescripcionButton.setText("Cambiar Descripcion");
        principalEditarEquipo.add(cambiarDescripcionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, 30));

        cambiarFechaProximaButton.setBackground(new java.awt.Color(242, 250, 255));
        cambiarFechaProximaButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cambiarFechaProximaButton.setText("Cambiar Fecha Proxima");
        principalEditarEquipo.add(cambiarFechaProximaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, 30));

        dayProxComboBox.setBackground(new java.awt.Color(242, 250, 255));
        dayProxComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //dayProxComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarEquipo.add(dayProxComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 30));

        monthProxComboBox.setBackground(new java.awt.Color(242, 250, 255));
        monthProxComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        monthProxComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarEquipo.add(monthProxComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, 30));

        yearProxComboBox.setBackground(new java.awt.Color(242, 250, 255));
        yearProxComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //yearProxComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalEditarEquipo.add(yearProxComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalEditarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalEditarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cambiarDescripcionButton;
    public javax.swing.JButton cambiarEstadoButton;
    public javax.swing.JButton cambiarFechaProximaButton;
    public JComboBox<Integer> dayProxComboBox;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> monthProxComboBox;
    public javax.swing.JPanel principalEditarEquipo;
    public javax.swing.JTextArea txtDescripcionEquipo;
    public javax.swing.JTextField txtEstadoEquipo;
    public JComboBox<Integer> yearProxComboBox;
    // End of variables declaration//GEN-END:variables
}
