/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class factura extends javax.swing.JFrame {

    /**
     * Creates new form registroGimnasio
     */
    public factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalFactura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        buscarUsuarioButton = new javax.swing.JButton();
        agregarDetalleButton = new javax.swing.JButton();
        pagarUnaReservaButton = new javax.swing.JButton();
        comboBoxActividades = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        ponerPrecioFinal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        reservarButton = new javax.swing.JButton();
        pnlInformacionUsuario = new javax.swing.JPanel();
        txtNombresUsuario = new javax.swing.JLabel();
        txtApellidosUsuario = new javax.swing.JLabel();
        txtDireccionUsuario = new javax.swing.JLabel();
        txtTelefonoUsuario = new javax.swing.JLabel();
        txtCedulaUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalFactura.setBackground(new java.awt.Color(255, 255, 255));
        principalFactura.setPreferredSize(new java.awt.Dimension(630, 552));
        principalFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Facturacion");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 29));
        principalFactura.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 630, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        principalFactura.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Cedula:");
        principalFactura.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Actividad:");
        principalFactura.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("Codigo: ");
        principalFactura.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 70, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 17)); // NOI18N
        jLabel6.setText("Cantidad de Meses:");
        principalFactura.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 17)); // NOI18N
        jLabel7.setText("Precio por Mes:");
        principalFactura.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Total:");
        principalFactura.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        txtNombre.setBackground(new java.awt.Color(242, 250, 255));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalFactura.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 210, 30));

        txtCedula.setBackground(new java.awt.Color(242, 250, 255));
        txtCedula.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalFactura.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 210, 30));

        txtCantidad.setBackground(new java.awt.Color(242, 250, 255));
        txtCantidad.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalFactura.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 150, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        principalFactura.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 570, 170));

        buscarUsuarioButton.setBackground(new java.awt.Color(242, 250, 255));
        buscarUsuarioButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        buscarUsuarioButton.setText("Buscar Usuario");
        principalFactura.add(buscarUsuarioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, 30));

        agregarDetalleButton.setBackground(new java.awt.Color(242, 250, 255));
        agregarDetalleButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        agregarDetalleButton.setText("Agregar Detalle");
        principalFactura.add(agregarDetalleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 140, 30));

        pagarUnaReservaButton.setBackground(new java.awt.Color(242, 250, 255));
        pagarUnaReservaButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        pagarUnaReservaButton.setText("Pagar una Reserva");
        principalFactura.add(pagarUnaReservaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 170, 30));

        comboBoxActividades.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxActividades.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxActividades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalFactura.add(comboBoxActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 30));

        txtCodigo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCodigo.setText(".");
        principalFactura.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 80, -1));

        txtPrecio.setBackground(new java.awt.Color(242, 250, 255));
        txtPrecio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalFactura.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 120, 30));

        ponerPrecioFinal.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        ponerPrecioFinal.setText("0.00");
        principalFactura.add(ponerPrecioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 90, -1));

        jLabel18.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jLabel18.setText("$");
        principalFactura.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 10, -1));

        btnGuardar.setBackground(new java.awt.Color(242, 250, 255));
        btnGuardar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnGuardar.setText("Pagar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        principalFactura.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 170, 30));

        reservarButton.setBackground(new java.awt.Color(242, 250, 255));
        reservarButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        reservarButton.setText("Reservar");
        principalFactura.add(reservarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 170, 30));

        pnlInformacionUsuario.setBackground(new java.awt.Color(255, 255, 255));

        txtNombresUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtNombresUsuario.setText("Nombre");

        txtApellidosUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtApellidosUsuario.setText("Apellidos");

        txtDireccionUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtDireccionUsuario.setText("Dirección");

        txtTelefonoUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtTelefonoUsuario.setText("Telefono");

        txtCedulaUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCedulaUsuario.setText("Cedula");

        javax.swing.GroupLayout pnlInformacionUsuarioLayout = new javax.swing.GroupLayout(pnlInformacionUsuario);
        pnlInformacionUsuario.setLayout(pnlInformacionUsuarioLayout);
        pnlInformacionUsuarioLayout.setHorizontalGroup(
            pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNombresUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtApellidosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtDireccionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(txtTelefonoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCedulaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlInformacionUsuarioLayout.setVerticalGroup(
            pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionUsuarioLayout.createSequentialGroup()
                .addComponent(txtNombresUsuario)
                .addGap(3, 3, 3)
                .addComponent(txtApellidosUsuario)
                .addGap(3, 3, 3)
                .addComponent(txtDireccionUsuario)
                .addGap(3, 3, 3)
                .addComponent(txtTelefonoUsuario)
                .addGap(3, 3, 3)
                .addComponent(txtCedulaUsuario)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        principalFactura.add(pnlInformacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 150, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarDetalleButton;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton buscarUsuarioButton;
    public javax.swing.JComboBox<String> comboBoxActividades;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton pagarUnaReservaButton;
    public javax.swing.JPanel pnlInformacionUsuario;
    public javax.swing.JLabel ponerPrecioFinal;
    public javax.swing.JPanel principalFactura;
    public javax.swing.JButton reservarButton;
    public javax.swing.JTable tabla;
    public javax.swing.JLabel txtApellidosUsuario;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JLabel txtCedulaUsuario;
    public javax.swing.JLabel txtCodigo;
    public javax.swing.JLabel txtDireccionUsuario;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JLabel txtNombresUsuario;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JLabel txtTelefonoUsuario;
    // End of variables declaration//GEN-END:variables
}
