/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vista;
import java.awt.Component;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
/**
 *
 * @author joshe
 */
public class HorarioSemanaSwing extends javax.swing.JFrame {
    
    private void setFullScreen() {
        // Obtener el GraphicsDevice del dispositivo de pantalla actual
        GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        
        // Configurar el JFrame para pantalla completa
        device.setFullScreenWindow(this); // Establecer el JFrame en pantalla completa

    }
    
    /**
     * Creates new form HorarioSemanaSwing
     */
    public HorarioSemanaSwing() {
        initComponents();
        //setFullScreen();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Horario Semanal");
        principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 20, 1200, -1));

        btnBuscar.setBackground(new java.awt.Color(242, 250, 255));
        btnBuscar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        principal.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 70, -1, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        // Tabla para mostrar el horario de la semana
        String[] diasSemana = {"Horas", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"};
        Object[][] data = new Object[24][diasSemana.length]; // Datos para la tabla, filas x columnas

        // Inicializar datos con horas del día como filas y días de la semana como columnas
        for (int i = 0; i < 24; i++) {
            data[i][0] = String.format("%02d:00", i); // Hora del día
            for (int j = 1; j < diasSemana.length; j++) {
                data[i][j] = ""; // Inicializar sin datos
            }
        }

        DefaultTableModel model = new DefaultTableModel(data, diasSemana);

        tablaHorario = new javax.swing.JTable(model) {
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
                Component component = super.prepareRenderer(renderer, row, column);
                int preferredHeight = Math.max(component.getPreferredSize().height, getRowHeight(row));
                setRowHeight(row, preferredHeight);
                return component;
            }
        };

        tablaHorario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N

        jScrollPane1.setViewportView(tablaHorario);

        principal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1200, 500)); //380

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        //setFullScreen();
        setLocationRelativeTo(null); // Centrar la ventana en la pantalla
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JTable getTablaHorario() {
        return tablaHorario;
    }

    public javax.swing.JButton getBtnBuscar() {
        return btnBuscar;
    }

    private static class MultiLineTableCellRenderer extends javax.swing.JTextArea implements TableCellRenderer {
        public MultiLineTableCellRenderer() {
            setLineWrap(true);
            setWrapStyleWord(true);
            setOpaque(true);
        }

        public Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column){
            setText((value == null) ? "" : value.toString());
            setPreferredSize(null);
            setSize(table.getColumnModel().getColumn(column).getWidth(), getPreferredSize().height);
            if (isSelected) {
                setBackground(table.getSelectionBackground());
                setForeground(table.getSelectionForeground());
            } else {
                setBackground(table.getBackground());
                setForeground(table.getForeground());
            }
            return this;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel principal;
    public javax.swing.JTable tablaHorario;
    // End of variables declaration//GEN-END:variables
}
