/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class inicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form inicioSesion
     */
    public inicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalInicioSesion = new javax.swing.JPanel();
        tituloInicioSesion = new javax.swing.JLabel();
        cedulaTitulo = new javax.swing.JLabel();
        claveTitulo = new javax.swing.JLabel();
        errores = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        btnverificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalInicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        principalInicioSesion.setPreferredSize(new java.awt.Dimension(400, 400));
        principalInicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloInicioSesion.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        tituloInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloInicioSesion.setText("Inciar Sesion");
        principalInicioSesion.add(tituloInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 20, 390, -1));

        cedulaTitulo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        cedulaTitulo.setText("Ingrese su Cedula:");
        principalInicioSesion.add(cedulaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        claveTitulo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        claveTitulo.setText("Ingrese su Clave:");
        principalInicioSesion.add(claveTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        errores.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        errores.setText("Errores");
        principalInicioSesion.add(errores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        txtCedula.setBackground(new java.awt.Color(242, 250, 255));
        txtCedula.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        principalInicioSesion.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 280, 40));

        txtClave.setBackground(new java.awt.Color(242, 250, 255));
        txtClave.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        principalInicioSesion.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 280, 40));

        btnverificar.setBackground(new java.awt.Color(242, 250, 255));
        btnverificar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnverificar.setText("Iniciar sesion");
        principalInicioSesion.add(btnverificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnverificar;
    public javax.swing.JLabel cedulaTitulo;
    public javax.swing.JLabel claveTitulo;
    public javax.swing.JLabel errores;
    public javax.swing.JPanel principalInicioSesion;
    public javax.swing.JLabel tituloInicioSesion;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtClave;
    // End of variables declaration//GEN-END:variables
}
