/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;

/**
 *
 * @author joshe
 */
public class pagarReserva extends javax.swing.JFrame {

    /**
     * Creates new form pagarReserva
     */
    public pagarReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCoincidencias = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetalles = new javax.swing.JTable();
        comboBox1 = new JComboBox<Integer>();
        pagarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagar Reserva");
        principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Busqueda de Facturas por:");
        principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Detalles");
        principal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Coincidencias");
        principal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tableCoincidencias.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tableCoincidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCoincidencias);

        principal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 460, 250));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tableDetalles.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tableDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDetalles);

        principal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 260, 250));

        comboBox1.setBackground(new java.awt.Color(242, 250, 255));
        comboBox1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //comboBox1.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principal.add(comboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 460, 30));

        pagarButton.setBackground(new java.awt.Color(242, 250, 255));
        pagarButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        pagarButton.setText("Pagar");
        principal.add(pagarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 130, 30));

        cancelarButton.setBackground(new java.awt.Color(242, 250, 255));
        cancelarButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cancelarButton.setText("Cancelar");
        principal.add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelarButton;
    public JComboBox<Integer> comboBox1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton pagarButton;
    public javax.swing.JPanel principal;
    public javax.swing.JTable tableCoincidencias;
    public javax.swing.JTable tableDetalles;
    // End of variables declaration//GEN-END:variables
}
