/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class registroJornada extends javax.swing.JFrame {

    /**
     * Creates new form registroJornada
     */
    public registroJornada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalRegistroJornada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        comboBoxHoraInicio = new javax.swing.JComboBox<>();
        comboBoxMinutoInicio = new javax.swing.JComboBox<>();
        comboBoxHoraFin = new javax.swing.JComboBox<>();
        comboBoxMinutoFin = new javax.swing.JComboBox<>();
        btnAgregarJornada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalRegistroJornada.setBackground(new java.awt.Color(255, 255, 255));
        principalRegistroJornada.setPreferredSize(new java.awt.Dimension(800, 200));
        principalRegistroJornada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Jornada");
        principalRegistroJornada.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        principalRegistroJornada.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Hora Inicio: ");
        principalRegistroJornada.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Hora Fin: ");
        principalRegistroJornada.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        txtNombre.setBackground(new java.awt.Color(242, 250, 255));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        principalRegistroJornada.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 150, -1));

        comboBoxHoraInicio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxHoraInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroJornada.add(comboBoxHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        comboBoxMinutoInicio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMinutoInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMinutoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroJornada.add(comboBoxMinutoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        comboBoxHoraFin.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxHoraFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxHoraFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroJornada.add(comboBoxHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        comboBoxMinutoFin.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMinutoFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMinutoFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroJornada.add(comboBoxMinutoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        btnAgregarJornada.setBackground(new java.awt.Color(242, 250, 255));
        btnAgregarJornada.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnAgregarJornada.setText("Agregar Jornada");
        principalRegistroJornada.add(btnAgregarJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistroJornada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistroJornada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarJornada;
    public javax.swing.JComboBox<String> comboBoxHoraFin;
    public javax.swing.JComboBox<String> comboBoxHoraInicio;
    public javax.swing.JComboBox<String> comboBoxMinutoFin;
    public javax.swing.JComboBox<String> comboBoxMinutoInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel principalRegistroJornada;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
