/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;

/**
 *
 * @author joshe
 */
public class registroEquipo extends javax.swing.JFrame {

    /**
     * Creates new form registroEquipo
     */
    public registroEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalRegistroEquipo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoEquipo = new javax.swing.JTextField();
        txtEstadoEquipo = new javax.swing.JTextField();
        txtCondigoMaterial = new javax.swing.JTextField();
        txtEstadoMaterial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionEquipo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionMaterial = new javax.swing.JTextArea();
        dayAdqComboBox = new JComboBox<Integer>();
        monthAdqComboBox = new javax.swing.JComboBox<>();
        yearAdqComboBox = new JComboBox<Integer>();
        dayProxComboBox = new JComboBox<Integer>();
        monthProxComboBox = new javax.swing.JComboBox<>();
        yearProxComboBox = new JComboBox<Integer>();
        dayComboBox = new JComboBox<Integer>();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new JComboBox<Integer>();
        btnAgregarMaterial = new javax.swing.JButton();
        btnAgregarEquipo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalRegistroEquipo.setBackground(new java.awt.Color(255, 255, 255));
        principalRegistroEquipo.setPreferredSize(new java.awt.Dimension(1000, 555));
        principalRegistroEquipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Equipo");
        principalRegistroEquipo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Codigo:");
        principalRegistroEquipo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Estado: ");
        principalRegistroEquipo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Fecha Adquisicion: ");
        principalRegistroEquipo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("Descripcion:");
        principalRegistroEquipo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel6.setText("Fecha Proxima: ");
        principalRegistroEquipo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setText("Codigo:");
        principalRegistroEquipo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Estado: ");
        principalRegistroEquipo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel9.setText("Fecha Mantenimiento: ");
        principalRegistroEquipo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Materiales");
        principalRegistroEquipo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1000, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel11.setText("Descripcion:");
        principalRegistroEquipo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        txtCodigoEquipo.setBackground(new java.awt.Color(242, 250, 255));
        txtCodigoEquipo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistroEquipo.add(txtCodigoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 320, 30));

        txtEstadoEquipo.setBackground(new java.awt.Color(242, 250, 255));
        txtEstadoEquipo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistroEquipo.add(txtEstadoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 320, 30));

        txtCondigoMaterial.setBackground(new java.awt.Color(242, 250, 255));
        txtCondigoMaterial.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistroEquipo.add(txtCondigoMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 320, 30));

        txtEstadoMaterial.setBackground(new java.awt.Color(242, 250, 255));
        txtEstadoMaterial.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistroEquipo.add(txtEstadoMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 320, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        txtDescripcionEquipo.setColumns(20);
        txtDescripcionEquipo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtDescripcionEquipo.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionEquipo);

        principalRegistroEquipo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 390, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        txtDescripcionMaterial.setColumns(20);
        txtDescripcionMaterial.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtDescripcionMaterial.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionMaterial);

        principalRegistroEquipo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 390, -1));

        dayAdqComboBox.setBackground(new java.awt.Color(242, 250, 255));
        dayAdqComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //dayAdqComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dayAdqComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayAdqComboBoxActionPerformed(evt);
            }
        });
        principalRegistroEquipo.add(dayAdqComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 80, 30));

        monthAdqComboBox.setBackground(new java.awt.Color(242, 250, 255));
        monthAdqComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        monthAdqComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroEquipo.add(monthAdqComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 80, 30));

        yearAdqComboBox.setBackground(new java.awt.Color(242, 250, 255));
        yearAdqComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //yearAdqComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroEquipo.add(yearAdqComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 80, 30));

        dayProxComboBox.setBackground(new java.awt.Color(242, 250, 255));
        dayProxComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //dayProxComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroEquipo.add(dayProxComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 80, 30));

        monthProxComboBox.setBackground(new java.awt.Color(242, 250, 255));
        monthProxComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        monthProxComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroEquipo.add(monthProxComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 80, 30));

        yearProxComboBox.setBackground(new java.awt.Color(242, 250, 255));
        yearProxComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //yearProxComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroEquipo.add(yearProxComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 80, 30));

        dayComboBox.setBackground(new java.awt.Color(242, 250, 255));
        dayComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //dayComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroEquipo.add(dayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 80, 30));

        monthComboBox.setBackground(new java.awt.Color(242, 250, 255));
        monthComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroEquipo.add(monthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 80, 30));

        yearComboBox.setBackground(new java.awt.Color(242, 250, 255));
        yearComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //yearComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroEquipo.add(yearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 80, 30));

        btnAgregarMaterial.setBackground(new java.awt.Color(242, 250, 255));
        btnAgregarMaterial.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnAgregarMaterial.setText("Agregar Material");
        principalRegistroEquipo.add(btnAgregarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 210, 30));

        btnAgregarEquipo.setBackground(new java.awt.Color(242, 250, 255));
        btnAgregarEquipo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnAgregarEquipo.setText("Agregar Equipo");
        principalRegistroEquipo.add(btnAgregarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 180, 40));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabla);

        principalRegistroEquipo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 940, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistroEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistroEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dayAdqComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayAdqComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayAdqComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarEquipo;
    public javax.swing.JButton btnAgregarMaterial;
    public JComboBox<Integer> dayAdqComboBox;
    public JComboBox<Integer> dayComboBox;
    public JComboBox<Integer> dayProxComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JComboBox<String> monthAdqComboBox;
    public javax.swing.JComboBox<String> monthComboBox;
    public javax.swing.JComboBox<String> monthProxComboBox;
    public javax.swing.JPanel principalRegistroEquipo;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtCodigoEquipo;
    public javax.swing.JTextField txtCondigoMaterial;
    public javax.swing.JTextArea txtDescripcionEquipo;
    public javax.swing.JTextArea txtDescripcionMaterial;
    public javax.swing.JTextField txtEstadoEquipo;
    public javax.swing.JTextField txtEstadoMaterial;
    public JComboBox<Integer> yearAdqComboBox;
    public JComboBox<Integer> yearComboBox;
    public JComboBox<Integer> yearProxComboBox;
    // End of variables declaration//GEN-END:variables
}
