/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;

/**
 *
 * @author joshe
 */
public class registrarActividad extends javax.swing.JFrame {

    /**
     * Creates new form registrarActividad
     */
    public registrarActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalRegistrarClase = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreAct = new javax.swing.JTextField();
        textFieldCodigo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        cbmEstado = new javax.swing.JComboBox<>();
        cmbInstructor = new javax.swing.JComboBox<>();
        actualizarUbicacionesButton = new javax.swing.JButton();
        cmbYearFechaInicio = new JComboBox<Integer>();
        comboBoxUbicaciones = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtCupo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        comboBoxGimnasios = new javax.swing.JComboBox<>();
        comboBoxMinutoFin = new javax.swing.JComboBox<>();
        cmbDiaFechaInicio = new JComboBox<Integer>();
        cmbMesFechaInicio = new javax.swing.JComboBox<>();
        cmbYearFechaFinal = new JComboBox<Integer>();
        cmbDiaFechaFin = new JComboBox<Integer>();
        cmbMesFechaFin = new javax.swing.JComboBox<>();
        comboBoxDiasSemana = new javax.swing.JComboBox<>();
        comboBoxMinutoInicio = new javax.swing.JComboBox<>();
        btnRegistrarClase = new javax.swing.JButton();
        comboBoxHoraInicio = new javax.swing.JComboBox<>();
        comboBoxHoraFin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalRegistrarClase.setBackground(new java.awt.Color(255, 255, 255));
        principalRegistrarClase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Clase");
        principalRegistrarClase.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        principalRegistrarClase.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 760, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Codigo");
        principalRegistrarClase.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 760, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Descripcion");
        principalRegistrarClase.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 760, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("Cupo");
        principalRegistrarClase.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 760, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel6.setText("Ubicaciones");
        principalRegistrarClase.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 760, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setText("Estado");
        principalRegistrarClase.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 320, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Instructor");
        principalRegistrarClase.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 440, -1));

        txtNombreAct.setBackground(new java.awt.Color(242, 250, 255));
        txtNombreAct.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarClase.add(txtNombreAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 720, 30));

        textFieldCodigo.setBackground(new java.awt.Color(242, 250, 255));
        textFieldCodigo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarClase.add(textFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 720, 30));

        txtDescripcion.setBackground(new java.awt.Color(242, 250, 255));
        txtDescripcion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarClase.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 720, 30));

        txtCosto.setBackground(new java.awt.Color(242, 250, 255));
        txtCosto.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarClase.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 720, 30));

        cbmEstado.setBackground(new java.awt.Color(242, 250, 255));
        cbmEstado.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cbmEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(cbmEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 220, 30));

        cmbInstructor.setBackground(new java.awt.Color(242, 250, 255));
        cmbInstructor.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbInstructor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(cmbInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 220, 30));

        actualizarUbicacionesButton.setBackground(new java.awt.Color(242, 250, 255));
        actualizarUbicacionesButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        actualizarUbicacionesButton.setText("Actualizar Ubicaciones");
        principalRegistrarClase.add(actualizarUbicacionesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 190, 30));

        cmbYearFechaInicio.setBackground(new java.awt.Color(242, 250, 255));
        cmbYearFechaInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //cmbYearFechaInicio.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(cmbYearFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 70, 30));

        comboBoxUbicaciones.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxUbicaciones.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxUbicaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(comboBoxUbicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 220, 30));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel9.setText("Errores");
        principalRegistrarClase.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 790, 800, -1));

        txtCupo.setBackground(new java.awt.Color(242, 250, 255));
        txtCupo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarClase.add(txtCupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 720, 30));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel10.setText("Costo");
        principalRegistrarClase.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 760, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel11.setText("Fecha Final");
        principalRegistrarClase.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 330, 20));

        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel12.setText("Horario");
        principalRegistrarClase.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 760, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel13.setText("Dia");
        principalRegistrarClase.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 750, -1));

        jLabel14.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel14.setText("Fecha Inicio");
        principalRegistrarClase.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 330, 20));

        jLabel15.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel15.setText("Hora Inicio:");
        principalRegistrarClase.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, 80, 20));

        jLabel16.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel16.setText("Hora Fin:");
        principalRegistrarClase.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 690, 80, 20));

        comboBoxGimnasios.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxGimnasios.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxGimnasios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(comboBoxGimnasios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 220, 30));

        comboBoxMinutoFin.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMinutoFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMinutoFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(comboBoxMinutoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 690, 100, 30));

        cmbDiaFechaInicio.setBackground(new java.awt.Color(242, 250, 255));
        cmbDiaFechaInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //cmbDiaFechaInicio.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(cmbDiaFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 70, 30));

        cmbMesFechaInicio.setBackground(new java.awt.Color(242, 250, 255));
        cmbMesFechaInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbMesFechaInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(cmbMesFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 70, 30));

        cmbYearFechaFinal.setBackground(new java.awt.Color(242, 250, 255));
        cmbYearFechaFinal.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //cmbYearFechaFinal.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(cmbYearFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 650, 70, 30));

        cmbDiaFechaFin.setBackground(new java.awt.Color(242, 250, 255));
        cmbDiaFechaFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //cmbDiaFechaFin.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(cmbDiaFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 70, 30));

        cmbMesFechaFin.setBackground(new java.awt.Color(242, 250, 255));
        cmbMesFechaFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbMesFechaFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(cmbMesFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 650, 70, 30));

        comboBoxDiasSemana.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxDiasSemana.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxDiasSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(comboBoxDiasSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 230, 30));

        comboBoxMinutoInicio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMinutoInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMinutoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(comboBoxMinutoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 690, 100, 30));

        btnRegistrarClase.setBackground(new java.awt.Color(242, 250, 255));
        btnRegistrarClase.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnRegistrarClase.setText("Registrar Clase");
        principalRegistrarClase.add(btnRegistrarClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 750, 230, 30));

        comboBoxHoraInicio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxHoraInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(comboBoxHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, 100, 30));

        comboBoxHoraFin.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxHoraFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxHoraFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarClase.add(comboBoxHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 690, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistrarClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistrarClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizarUbicacionesButton;
    public javax.swing.JButton btnRegistrarClase;
    public javax.swing.JComboBox<String> cbmEstado;
    public JComboBox<Integer> cmbDiaFechaFin;
    public JComboBox<Integer> cmbDiaFechaInicio;
    public javax.swing.JComboBox<String> cmbInstructor;
    public javax.swing.JComboBox<String> cmbMesFechaFin;
    public javax.swing.JComboBox<String> cmbMesFechaInicio;
    public JComboBox<Integer> cmbYearFechaFinal;
    public JComboBox<Integer> cmbYearFechaInicio;
    public javax.swing.JComboBox<String> comboBoxDiasSemana;
    public javax.swing.JComboBox<String> comboBoxGimnasios;
    public javax.swing.JComboBox<String> comboBoxHoraFin;
    public javax.swing.JComboBox<String> comboBoxHoraInicio;
    public javax.swing.JComboBox<String> comboBoxMinutoFin;
    public javax.swing.JComboBox<String> comboBoxMinutoInicio;
    public javax.swing.JComboBox<String> comboBoxUbicaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel principalRegistrarClase;
    public javax.swing.JTextField textFieldCodigo;
    public javax.swing.JTextField txtCosto;
    public javax.swing.JTextField txtCupo;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtNombreAct;
    // End of variables declaration//GEN-END:variables
}
