/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;

/**
 *
 * @author joshe
 */
public class registroMiembros extends javax.swing.JFrame {

    /**
     * Creates new form registroMiembros
     */
    public registroMiembros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalRegistroUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        dayComboBox = new JComboBox<Integer>();
        monthComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new JComboBox<Integer>();
        escogerFotoButton = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalRegistroUsuario.setBackground(new java.awt.Color(255, 255, 255));
        principalRegistroUsuario.setPreferredSize(new java.awt.Dimension(400, 450));
        principalRegistroUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrarse");
        principalRegistroUsuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombres");
        principalRegistroUsuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos");
        principalRegistroUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Telefono");
        principalRegistroUsuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("Dirección");
        principalRegistroUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel6.setText("Cedula");
        principalRegistroUsuario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setText("Fecha de Fin de Membresía");
        principalRegistroUsuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Foto Escogida:");
        principalRegistroUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 342, -1, 20));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel9.setText("Errores");
        principalRegistroUsuario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 400, -1));

        txtNombres.setBackground(new java.awt.Color(242, 250, 255));
        txtNombres.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistroUsuario.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 260, 30));

        txtApellidos.setBackground(new java.awt.Color(242, 250, 255));
        txtApellidos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistroUsuario.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 260, 30));

        txtTelefono.setBackground(new java.awt.Color(242, 250, 255));
        txtTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistroUsuario.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 260, 30));

        txtDireccion.setBackground(new java.awt.Color(242, 250, 255));
        txtDireccion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistroUsuario.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 30));

        txtCedula.setBackground(new java.awt.Color(242, 250, 255));
        txtCedula.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistroUsuario.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 260, 30));

        dayComboBox.setBackground(new java.awt.Color(242, 250, 255));
        dayComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //dayComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroUsuario.add(dayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 30));

        monthComboBox.setBackground(new java.awt.Color(242, 250, 255));
        monthComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroUsuario.add(monthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 110, 30));

        yearComboBox.setBackground(new java.awt.Color(242, 250, 255));
        yearComboBox.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        //yearComboBox.setModel(new DefaultComboBoxModel<Integer>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistroUsuario.add(yearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 110, 30));

        escogerFotoButton.setBackground(new java.awt.Color(242, 250, 255));
        escogerFotoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        escogerFotoButton.setText("Escoger Foto");
        principalRegistroUsuario.add(escogerFotoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, 30));

        btnRegistrarse.setBackground(new java.awt.Color(242, 250, 255));
        btnRegistrarse.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        principalRegistroUsuario.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 150, 40));

        foto.setText(".");
        principalRegistroUsuario.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 90, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarse;
    public JComboBox<Integer> dayComboBox;
    public javax.swing.JButton escogerFotoButton;
    public javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JComboBox<String> monthComboBox;
    public javax.swing.JPanel principalRegistroUsuario;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtTelefono;
    public JComboBox<Integer> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
