/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class registrarGimnasio extends javax.swing.JFrame {

    /**
     * Creates new form registroGimnasio
     */
    public registrarGimnasio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalRegistrarGimnasio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreGim = new javax.swing.JTextField();
        txtDireccionGim = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefonoGim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUbicaciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEquipos = new javax.swing.JTable();
        agregarEquiposButton = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnRegistrarGimnasio = new javax.swing.JButton();
        comboBoxHoraInicio = new javax.swing.JComboBox<>();
        comboBoxMinutoInicio = new javax.swing.JComboBox<>();
        comboBoxHoraFin = new javax.swing.JComboBox<>();
        comboBoxMinutoFin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalRegistrarGimnasio.setBackground(new java.awt.Color(255, 255, 255));
        principalRegistrarGimnasio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Gimnasio");
        principalRegistrarGimnasio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        principalRegistrarGimnasio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 970, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Direccion");
        principalRegistrarGimnasio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 970, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Ubicaciones");
        principalRegistrarGimnasio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 970, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("Codigo: ");
        principalRegistrarGimnasio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        principalRegistrarGimnasio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setText("Telefono");
        principalRegistrarGimnasio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Horario");
        principalRegistrarGimnasio.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel9.setText("Hora Inicio: ");
        principalRegistrarGimnasio.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jLabel10.setText("Hora Fin: ");
        principalRegistrarGimnasio.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel11.setText("Errores");
        principalRegistrarGimnasio.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1000, -1));

        txtNombreGim.setBackground(new java.awt.Color(242, 250, 255));
        txtNombreGim.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarGimnasio.add(txtNombreGim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 940, 30));

        txtDireccionGim.setBackground(new java.awt.Color(242, 250, 255));
        txtDireccionGim.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarGimnasio.add(txtDireccionGim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 940, 30));

        txtCodigo.setBackground(new java.awt.Color(242, 250, 255));
        txtCodigo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarGimnasio.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, 30));

        txtNombre.setBackground(new java.awt.Color(242, 250, 255));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarGimnasio.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 150, 30));

        txtTelefonoGim.setBackground(new java.awt.Color(242, 250, 255));
        txtTelefonoGim.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtTelefonoGim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoGimActionPerformed(evt);
            }
        });
        principalRegistrarGimnasio.add(txtTelefonoGim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 940, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tablaUbicaciones.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tablaUbicaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUbicaciones);

        principalRegistrarGimnasio.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 390, 160));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tablaEquipos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        tablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaEquipos);

        principalRegistrarGimnasio.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 230, 80));

        agregarEquiposButton.setBackground(new java.awt.Color(242, 250, 255));
        agregarEquiposButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        agregarEquiposButton.setText("Agregar Equipos");
        principalRegistrarGimnasio.add(agregarEquiposButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 180, 30));

        btnAgregar.setBackground(new java.awt.Color(242, 250, 255));
        btnAgregar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnAgregar.setText("Registrar Equipo");
        principalRegistrarGimnasio.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 150, 30));

        btnRegistrarGimnasio.setBackground(new java.awt.Color(242, 250, 255));
        btnRegistrarGimnasio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        btnRegistrarGimnasio.setText("Registrar Gimnasio");
        principalRegistrarGimnasio.add(btnRegistrarGimnasio, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 170, 40));

        comboBoxHoraInicio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxHoraInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarGimnasio.add(comboBoxHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 80, 30));

        comboBoxMinutoInicio.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMinutoInicio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMinutoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarGimnasio.add(comboBoxMinutoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 80, 30));

        comboBoxHoraFin.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxHoraFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxHoraFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarGimnasio.add(comboBoxHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 80, 30));

        comboBoxMinutoFin.setBackground(new java.awt.Color(242, 250, 255));
        comboBoxMinutoFin.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        comboBoxMinutoFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarGimnasio.add(comboBoxMinutoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistrarGimnasio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistrarGimnasio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoGimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoGimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoGimActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarEquiposButton;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnRegistrarGimnasio;
    public javax.swing.JComboBox<String> comboBoxHoraFin;
    public javax.swing.JComboBox<String> comboBoxHoraInicio;
    public javax.swing.JComboBox<String> comboBoxMinutoFin;
    public javax.swing.JComboBox<String> comboBoxMinutoInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel principalRegistrarGimnasio;
    public javax.swing.JTable tablaEquipos;
    public javax.swing.JTable tablaUbicaciones;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtDireccionGim;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombreGim;
    public javax.swing.JTextField txtTelefonoGim;
    // End of variables declaration//GEN-END:variables
}
