/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class registroPersonal extends javax.swing.JFrame {

    /**
     * Creates new form registroMiembros
     */
    public registroPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalRegistrarPersonal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        cmbJornada = new javax.swing.JComboBox<>();
        escogerFotoButton = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        foto = new javax.swing.JLabel();
        txtRol = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        principalRegistrarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        principalRegistrarPersonal.setPreferredSize(new java.awt.Dimension(400, 450));
        principalRegistrarPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Personal");
        principalRegistrarPersonal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombres");
        principalRegistrarPersonal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos");
        principalRegistrarPersonal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Telefono");
        principalRegistrarPersonal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setText("Dirección");
        principalRegistrarPersonal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel6.setText("Cedula");
        principalRegistrarPersonal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setText("Jornada");
        principalRegistrarPersonal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 20));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Foto Escogida:");
        principalRegistrarPersonal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, 20));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel9.setText("Errores");
        principalRegistrarPersonal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 400, -1));

        txtNombres.setBackground(new java.awt.Color(242, 250, 255));
        txtNombres.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarPersonal.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 260, 30));

        txtApellidos.setBackground(new java.awt.Color(242, 250, 255));
        txtApellidos.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarPersonal.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 260, 30));

        txtTelefono.setBackground(new java.awt.Color(242, 250, 255));
        txtTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarPersonal.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 30));

        txtDireccion.setBackground(new java.awt.Color(242, 250, 255));
        txtDireccion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarPersonal.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 260, 30));

        txtCedula.setBackground(new java.awt.Color(242, 250, 255));
        txtCedula.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarPersonal.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 260, 30));

        cmbJornada.setBackground(new java.awt.Color(242, 250, 255));
        cmbJornada.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cmbJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        principalRegistrarPersonal.add(cmbJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 260, 30));

        escogerFotoButton.setBackground(new java.awt.Color(242, 250, 255));
        escogerFotoButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        escogerFotoButton.setText("Escoger Foto");
        principalRegistrarPersonal.add(escogerFotoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 120, 30));

        btnRegistrarse.setBackground(new java.awt.Color(242, 250, 255));
        btnRegistrarse.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        principalRegistrarPersonal.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 150, 40));

        foto.setText(".");
        principalRegistrarPersonal.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 90, 90));

        txtRol.setBackground(new java.awt.Color(242, 250, 255));
        txtRol.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        principalRegistrarPersonal.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 260, 30));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel10.setText("Clave");
        principalRegistrarPersonal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel11.setText("Rol");
        principalRegistrarPersonal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        txtClave.setBackground(new java.awt.Color(242, 250, 255));
        principalRegistrarPersonal.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistrarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalRegistrarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarse;
    public javax.swing.JComboBox<String> cmbJornada;
    public javax.swing.JButton escogerFotoButton;
    public javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel principalRegistrarPersonal;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JPasswordField txtClave;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtRol;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
