/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author joshe
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        labelInfoSesion = new javax.swing.JLabel();
        btnFacturar = new javax.swing.JButton();
        btnSegunUsuario6 = new javax.swing.JButton();
        btnSegunUsuario7 = new javax.swing.JButton();
        btniniciarSesion = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        btnSegunUsuario8 = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        pnlInformacionUsuario = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        tituloUsuario = new javax.swing.JLabel();
        txtNombresUsuario = new javax.swing.JLabel();
        txtApellidosUsuario = new javax.swing.JLabel();
        txtEstadoUsuario = new javax.swing.JLabel();
        txtDireccionUsuario = new javax.swing.JLabel();
        txtTelefonoUsuario = new javax.swing.JLabel();
        txtRolUsuario = new javax.swing.JLabel();
        txtCedulaUsuario = new javax.swing.JLabel();
        btnSegunUsuario5 = new javax.swing.JButton();
        pnlSegunUsuario = new javax.swing.JPanel();
        btnSegunUsuario = new javax.swing.JButton();
        btnSegunUsuario2 = new javax.swing.JButton();
        btnSegunUsuario3 = new javax.swing.JButton();
        btnSegunUsuario4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setPreferredSize(new java.awt.Dimension(1000, 550));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPrincipal.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        tituloPrincipal.setText("Administración del Gimnasio-Pantalla Principal");
        principal.add(tituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        labelInfoSesion.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        labelInfoSesion.setText("Debes Iniciar Sesión primero");
        principal.add(labelInfoSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        btnFacturar.setBackground(new java.awt.Color(242, 250, 255));
        btnFacturar.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnFacturar.setText("Facturar");
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });
        principal.add(btnFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 210, 40));

        btnSegunUsuario6.setBackground(new java.awt.Color(242, 250, 255));
        btnSegunUsuario6.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnSegunUsuario6.setText("jButton1");
        principal.add(btnSegunUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 210, 40));

        btnSegunUsuario7.setBackground(new java.awt.Color(242, 250, 255));
        btnSegunUsuario7.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnSegunUsuario7.setText("jButton1");
        principal.add(btnSegunUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 210, 40));

        btniniciarSesion.setBackground(new java.awt.Color(242, 250, 255));
        btniniciarSesion.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btniniciarSesion.setText("Inciar Sesion");
        principal.add(btniniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 210, 40));

        btnRegistrarse.setBackground(new java.awt.Color(242, 250, 255));
        btnRegistrarse.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        principal.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 210, 40));

        btnSegunUsuario8.setBackground(new java.awt.Color(242, 250, 255));
        btnSegunUsuario8.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnSegunUsuario8.setText("jButton1");
        principal.add(btnSegunUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 210, 40));

        btnCerrarSesion.setBackground(new java.awt.Color(242, 250, 255));
        btnCerrarSesion.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        principal.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 210, 40));

        pnlInformacionUsuario.setBackground(new java.awt.Color(246, 246, 246));

        foto.setText(".");

        tituloUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        tituloUsuario.setText("Usuario Actual:");

        txtNombresUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtNombresUsuario.setText("Nombre");

        txtApellidosUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtApellidosUsuario.setText("Apellidos");

        txtEstadoUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtEstadoUsuario.setText("Estado");

        txtDireccionUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtDireccionUsuario.setText("Direccion");

        txtTelefonoUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtTelefonoUsuario.setText("Telefono");

        txtRolUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtRolUsuario.setText("Rol");

        txtCedulaUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtCedulaUsuario.setText("Cedula");

        btnSegunUsuario5.setBackground(new java.awt.Color(242, 250, 255));
        btnSegunUsuario5.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnSegunUsuario5.setText("Actualizar Datos");
        btnSegunUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegunUsuario5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInformacionUsuarioLayout = new javax.swing.GroupLayout(pnlInformacionUsuario);
        pnlInformacionUsuario.setLayout(pnlInformacionUsuarioLayout);
        pnlInformacionUsuarioLayout.setHorizontalGroup(
            pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionUsuarioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloUsuario)
                    .addComponent(txtNombresUsuario)
                    .addComponent(txtApellidosUsuario)
                    .addComponent(txtEstadoUsuario)
                    .addComponent(txtDireccionUsuario)
                    .addComponent(txtTelefonoUsuario)
                    .addComponent(txtRolUsuario)
                    .addComponent(txtCedulaUsuario)
                    .addComponent(btnSegunUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlInformacionUsuarioLayout.setVerticalGroup(
            pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionUsuarioLayout.createSequentialGroup()
                .addGroup(pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionUsuarioLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(tituloUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombresUsuario)
                        .addGap(8, 8, 8)
                        .addComponent(txtApellidosUsuario)
                        .addGap(8, 8, 8)
                        .addComponent(txtEstadoUsuario)
                        .addGap(8, 8, 8)
                        .addComponent(txtDireccionUsuario))
                    .addComponent(foto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(txtTelefonoUsuario)
                .addGap(8, 8, 8)
                .addComponent(txtRolUsuario)
                .addGap(8, 8, 8)
                .addComponent(txtCedulaUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnSegunUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        principal.add(pnlInformacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 420, 360));

        pnlSegunUsuario.setBackground(new java.awt.Color(246, 246, 246));

        btnSegunUsuario.setBackground(new java.awt.Color(242, 250, 255));
        btnSegunUsuario.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnSegunUsuario.setText("SegunUsuario");

        btnSegunUsuario2.setBackground(new java.awt.Color(242, 250, 255));
        btnSegunUsuario2.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnSegunUsuario2.setText("SegunUsuario2");

        btnSegunUsuario3.setBackground(new java.awt.Color(242, 250, 255));
        btnSegunUsuario3.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnSegunUsuario3.setText("SegunUsuario3");
        btnSegunUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegunUsuario3ActionPerformed(evt);
            }
        });

        btnSegunUsuario4.setBackground(new java.awt.Color(242, 250, 255));
        btnSegunUsuario4.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        btnSegunUsuario4.setText("SegunUsuario4");

        javax.swing.GroupLayout pnlSegunUsuarioLayout = new javax.swing.GroupLayout(pnlSegunUsuario);
        pnlSegunUsuario.setLayout(pnlSegunUsuarioLayout);
        pnlSegunUsuarioLayout.setHorizontalGroup(
            pnlSegunUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSegunUsuarioLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlSegunUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSegunUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSegunUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSegunUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSegunUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        pnlSegunUsuarioLayout.setVerticalGroup(
            pnlSegunUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSegunUsuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnSegunUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnSegunUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnSegunUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnSegunUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        principal.add(pnlSegunUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 240, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSegunUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegunUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSegunUsuario3ActionPerformed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturarActionPerformed

    private void btnSegunUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegunUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSegunUsuario5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnFacturar;
    public javax.swing.JButton btnRegistrarse;
    public javax.swing.JButton btnSegunUsuario;
    public javax.swing.JButton btnSegunUsuario2;
    public javax.swing.JButton btnSegunUsuario3;
    public javax.swing.JButton btnSegunUsuario4;
    public javax.swing.JButton btnSegunUsuario5;
    public javax.swing.JButton btnSegunUsuario6;
    public javax.swing.JButton btnSegunUsuario7;
    public javax.swing.JButton btnSegunUsuario8;
    public javax.swing.JButton btniniciarSesion;
    public javax.swing.JLabel foto;
    public javax.swing.JLabel labelInfoSesion;
    public javax.swing.JPanel pnlInformacionUsuario;
    public javax.swing.JPanel pnlSegunUsuario;
    public javax.swing.JPanel principal;
    public javax.swing.JLabel tituloPrincipal;
    public javax.swing.JLabel tituloUsuario;
    public javax.swing.JLabel txtApellidosUsuario;
    public javax.swing.JLabel txtCedulaUsuario;
    public javax.swing.JLabel txtDireccionUsuario;
    public javax.swing.JLabel txtEstadoUsuario;
    public javax.swing.JLabel txtNombresUsuario;
    public javax.swing.JLabel txtRolUsuario;
    public javax.swing.JLabel txtTelefonoUsuario;
    // End of variables declaration//GEN-END:variables
}
